// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0PJvoaVIIxHtY44HT0wF1h6qz1B5Fdvk',
    appId: '1:462362457667:web:577c84df3ecc980043c6f6',
    messagingSenderId: '462362457667',
    projectId: 'sleepwell-app-2025',
    authDomain: 'sleepwell-app-2025.firebaseapp.com',
    storageBucket: 'sleepwell-app-2025.firebasestorage.app',
    measurementId: 'G-WC56775DKJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgcbCTf-00CaAxptCfVlTnNlloVrrFjws',
    appId: '1:462362457667:android:a8ce2db90209d6a543c6f6',
    messagingSenderId: '462362457667',
    projectId: 'sleepwell-app-2025',
    storageBucket: 'sleepwell-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuUPNtvXTt5_5LBP_5X_S4hV9-k-ZQP9w',
    appId: '1:462362457667:ios:65b2aafced56b37443c6f6',
    messagingSenderId: '462362457667',
    projectId: 'sleepwell-app-2025',
    storageBucket: 'sleepwell-app-2025.firebasestorage.app',
    iosBundleId: 'com.example.sleepApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuUPNtvXTt5_5LBP_5X_S4hV9-k-ZQP9w',
    appId: '1:462362457667:ios:65b2aafced56b37443c6f6',
    messagingSenderId: '462362457667',
    projectId: 'sleepwell-app-2025',
    storageBucket: 'sleepwell-app-2025.firebasestorage.app',
    iosBundleId: 'com.example.sleepApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0PJvoaVIIxHtY44HT0wF1h6qz1B5Fdvk',
    appId: '1:462362457667:web:2a6093a181608ab843c6f6',
    messagingSenderId: '462362457667',
    projectId: 'sleepwell-app-2025',
    authDomain: 'sleepwell-app-2025.firebaseapp.com',
    storageBucket: 'sleepwell-app-2025.firebasestorage.app',
    measurementId: 'G-0EM62MFG2Y',
  );
}
